name: FastGPT GitHub Actions Workflow

  
  pull_request_target:
    branches:
      - main

jobs:
  build-and-deploy:

env:
  FASTGPT_TOKEN: ${{ secrets.FASTGPT_TOKEN }}

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests and coverage
        run: pytest --cov
      - name: Build and deploy
        run: |
          echo Deploying FastGPT application
        run: pytest -v --cov

      - name: Deploy FastGPT application
        run: |
          # Add deployment commands here

env:
  FASTGPT_TOKEN: ${{ secrets.FASTGPT_TOKEN }}
